# Generated by Django 4.2.5 on 2024-03-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobaccepted',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
