# Generated by Django 4.2.5 on 2024-03-14 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobaccepted',
            name='is_work_started',
            field=models.BooleanField(default=False),
        ),
    ]
